apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- my-resource.yaml
patchesStrategicMerge:
- config.yaml
secretGenerator:
- name: db-user-pass
  files:
  - changefeed.sql
replacements:
- path: replacements.yaml
namespace: argo
