apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
patchesStrategicMerge:
- config.yaml
secretGenerator:
- name: db-user-pass
  files:
  - changefeed.sql
namespace: argo
